### ISSUE TITLE
OnHold count incorrect as of 1/31/18

### ISSUE THREAD

**Issue by faw872** [NickTheITGuy/OSTicket-OnHold#3]
Thanks for posting this Nick.  It helped me get jump started.  I did have to make some changes though. 
 I'm sure my code could be improved upon as well.  The number of onhold tickets was incorrect because the SQL added to tickets.php didn't account for permissions.  I decided to go up a level to class.ticket.php and modified the following function like so.  I assumed that the onhold id was 6 like was done in the rest of the code.

`function getStaffStats($staff) {
        global $cfg;

        /* Unknown or invalid staff */
        if(!$staff || (!is_object($staff) && !($staff=Staff::lookup($staff))) || !$staff->isStaff())
            return null;

        // -- Open and assigned to me
        $assigned = Q::any(array(
            'staff_id' => $staff->getId(),
        ));
        // -- Open and assigned to a team of mine
        if ($teams = array_filter($staff->getTeams()))
            $assigned->add(array('team_id__in' => $teams));

        $visibility = Q::any(new Q(array('status__state'=>'open', $assigned)));

        // -- Routed to a department of mine
        if (!$staff->showAssignedOnly() && ($depts = $staff->getDepts()))
            $visibility->add(array('dept_id__in' => $depts));

        $blocks = Ticket::objects()
            ->filter(Q::any($visibility))
            ->filter(array('status__state' => 'open'))
            ->aggregate(array('count' => SqlAggregate::COUNT('ticket_id')))
            ->values('status__state', 'isanswered', 'isoverdue','staff_id', 'team_id', 'status_id');

        $stats = array();
        $hideassigned = ($cfg && !$cfg->showAssignedTickets()) && !$staff->showAssignedTickets();
        $showanswered = $cfg->showAnsweredTickets();
        $id = $staff->getId();
        foreach ($blocks as $S) {
            if ($showanswered || !$S['isanswered']) {
                if (!($hideassigned && ($S['staff_id'] || $S['team_id']))){
                    if($S['status_id'] != 6){
                        $stats['open'] += $S['count'];
                    }
                }
            }
            else {
                if($S['status_id'] != 6){
                    $stats['answered'] += $S['count'];
                }
            }
            if ($S['isoverdue']  && $S['status_id'] != 6)
                $stats['overdue'] += $S['count'];
            if($S['status_id'] == 6)
                $stats['onhold'] += $S['count'];
            if ($S['staff_id'] == $id)
                $stats['assigned'] += $S['count'];
            elseif ($S['team_id']
                    && $S['staff_id'] == 0
                    && $teams
                    && in_array($S['team_id'], $teams))
                // Assigned to my team but uassigned to an agent
                $stats['assigned'] += $S['count'];
        }
        return $stats;
    }`
This also means that tickets.php no longer needs the query to get onhold count.  I also made one change to the first line in this block of code you added to tickets.php:
`$nav->addSubMenu(array('desc' => __('Onhold').' ('.number_format($stats['onhold']).')',
                       'title'=>__('Onhold Tickets'),
                       'href'=>'tickets.php?status=onhold',
                       'iconclass'=>'onholdTickets'),
                    ($_REQUEST['status']=='onhold'));`

**Comment by perryk** [comment]
Thanks for logging this and submitting the PR.

I've done something similar however I have been swamped and unable to upload it here. Combined with not being sure if Nick wanted to change from this repo having just the files for the mod and not being a fork on the main osticket repo. 

Something else which held me up is I found a number of weeks ago a merge conflict with this and an PR I really wanted to try on which fixes a big bug with using Teams in OsTicket. 

It took me a long while to work it all out however in the end I think I have it all working and you can find it here:

https://github.com/perryk/osTicket/commit/f2fd36d760481c655a0bc1c48bd6d247115740fb

@faw872 it would be great if you were able to compare your code to mine also and see if there anything we could both improve upon. I'm not really a developer, just trying to have things working bug free in our install of OsTicket.

If you are looking to apply my changes to a default osticket install you can do something like the following:

```
        git remote add perryk https://github.com/perryk/osTicket.git
        git pull --no-edit perryk mod-onhold-by-nicktheitguy
```

From just a brief look I think my code might have a small bug with overdue tickets which we rarely use, otherwise things look very similar which is a good sign. My code for "Assigned" is a little different due to the fix for the bug with teams. This is detailed in OsTicket PR 3608.

@NickTheITGuy If you are happy with these changes and they test out ok for you I don't see any trouble in merging in the PR. 

Cheers.

Perry.

**Comment by NickTheITGuy** [comment]
Most updated and refined version can be found on Perry's github.

@perryk took me a long time to respond, i know :p 

Best regards,
Nick

**Comment by perryk** [comment]
Hi @NickTheITGuy, all good, I completely understand :)
